### ISSUE TITLE
saber-ajax 2.x版本不兼容之前的版本

### ISSUE THREAD

**Issue by kekee000** [ecomfe/saber-ajax#4]
saber-ajax 0.x的两个接口
saber-ajax/ajax
saber-ajax/ejson
现在2.x版本ejson被放入ajax了，导致很多基于ejson的组件需要修改，不利于组件复用，
希望再加上此接口

**Comment by treelite** [comment]
2.0 版本最主要的升级是同构化，在 AMD 的环境由于 packages 的配置  `saber-ajax/ejson` 会指向 `saber-ajax/src/ejson.js` 。在 node 环境下 没有那样的 packages 配置 此时 `saber-ajax/ejson` 就会指向 `saber-ajax/ejson.js` ，而实际上开发的时候我们并不希望把所有 node 端的代码都放在 module 的根目录下，所以最后权衡放弃了以前这种接口的提供方式。

如果没有同构化的需求又想继续使用以前的那种接口方式的话，建议使用 1.x 版本，1.x 与 2.x 都会持续维护，可以放心使用～
